# http://docs.docker.jp/compose/rails.html
# https://hub.docker.com/_/mysql/
version: '3.7'
services:

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./postgres:/var/lib/postgresql


  # mysql:
  #   image: mysql
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - ./mysql:/var/lib/mysql


  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./mongo:/data

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password


  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - '4567-4584:4567-4584'
  #     - '5000:5000'
  #   environment:
  #     DEFAULT_REGION: ap-notrheast-1
  #     HOSTNAME: localstack
  #     HOSTNAME_EXTERNAL: localstack
  #     DATA_DIR: /tmp/localstack/data
  #     PORT_WEB_UI: 5000
  #     USE_SSL: 1
  #   volumes:
  #     - ./localstack:/tmp/localstack

  # sam:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/sam.Dockerfile
  #   container_name: sam
  #   # command: bash -c 'sam local start-api --host 0.0.0.0'
  #   ports:
  #     - '3030:3000'
  # #   depends_on:
  # #     - localstack
  #   environment:
  #     SAM_DOCKER_VOLUME_BASEDIR: ${PWD}/sam
  #   env_file:
  #     - ./Envfiles/sam.env
  #   volumes:
  #     - ./sam:/app:cached
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   tty: true

  # sls:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/sls.Dockerfile
  #   container_name: sls
  #   # command: bash -c 'sls'
  #   ports:
  #     - '3030:3000'
  # #   depends_on:
  # #     - localstack
  #   env_file:
  #     - ./Envfiles/sls.env
  #   volumes:
  #     - ./sls:/app:cached
  #   tty: true

  # dynamodb-admin:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/dynamodb-admin.Dockerfile
  #   command: dynamodb-admin
  #   ports:
  #     - '5001:8001'
  #   depends_on:
  #     - localstack
  #   environment:
  #     DYNAMO_ENDPOINT: http://localstack:4569
  #     AWS_REGION: ap-notrheast-1


  # ruby:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/ruby.Dockerfile
  #   container_name: ruby
  #   ports:
  #     - '3000:3000'
  #   # command: bash -c 'rm -f tmp/pids/* && rm -f .overmind.sock && overmind start'
  #   environment:
  #     LANG: C.UTF-8
  #     EDITOR: vim
  #     BUNDLE_APP_CONFIG: /app/.bundle
  #   env_file:
  #     - ./Envfiles/ruby.env
  #   # depends_on:
  #     # - postgres
  #     # - mysql
  #   volumes:
  #     - ./ruby:/app:cached
  #     - ./ruby/bundle:/app/bundle
  #   tty: true

  # node:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/node.Dockerfile
  #   container_name: node
  #   # command: bash -c 'gatsby develop --host 0.0.0.0'
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - ./Envfiles/node.env
  #   volumes:
  #     - ./node:/app:cached
  #     - ./node/node_modules:/app/node_modules
  #   tty: true


  # https-portal:
  #   image: steveltn/https-portal:1
  #   container_name: https-portal
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     # - rails
  #     - node
  #   depends_on:
  #     # - rails
  #     - node
  #   environment:
  #     WEBSOCKET: 'true'
  #     DOMAINS: 'loopback.forgxisto.com -> http://node:8000/'
  #     STAGE: local
  #   volumes:
  #     - ./https-portal:/var/lib/https-portal
