# http://docs.docker.jp/compose/rails.html
# https://hub.docker.com/_/mysql/
version: '3.7'

networks:
  default:
    name: docker-lan

x-ruby: &ruby
  build:
    context: .
    args:
      RUBY_VERSION: '3.1.0'
      PG_MAJOR: '14'
      NODE_MAJOR: '16'
      YARN_VERSION: '1.22.17'
    dockerfile: ./Dockerfiles/ruby.Dockerfile
    target: ${RAILS_ENV}
  container_name: ruby
  env_file:
    - ./Envfiles/ruby.env
  depends_on:
    - postgres
    # - mysql
  volumes:
    - ./App/ruby:/app:cached
  tty: true

services:

  # rails:
  #   <<: *ruby
  #   container_name: rails
  #   ports:
  #     - '3000:3000'
  #   command: 'bundle exec rails server -b 0.0.0.0'

  # sidekiq:
  #   <<: *ruby
  #   container_name: sidekiq
  #   command: 'bundle exec sidekiq -C config/sidekiq.yml'

  # node:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/node.Dockerfile
  #   container_name: node
  #   # command: bash -c 'gatsby develop --host 0.0.0.0'
  #   ports:
  #     - '8000:8000'
  #   env_file:
  #     - ./Envfiles/node.env
  #   volumes:
  #     - ./App/node:/app:cached
  #     - ./App/node/node_modules:/app/node_modules
  #   tty: true

  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./LocalData/postgres:/var/lib/postgresql

  # mysql:
  #   image: mysql
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - ./LocalData/mysql:/var/lib/mysql

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./LocalData/mongo:/data

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password

  # localstack:
  #   image: localstack/localstack
  #   environment:
  #     DEFAULT_REGION: ap-notrheast-1
  #     HOSTNAME: localstack
  #     HOSTNAME_EXTERNAL: localstack
  #     DATA_DIR: /tmp/localstack/data
  #     SERVICES: serverless
  #   volumes:
  #     - ./LocalData/localstack:/tmp/localstack

  # dynamodb-admin:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/dynamodb-admin.Dockerfile
  #   command: dynamodb-admin
  #   ports:
  #     - '5001:8001'
  #   depends_on:
  #     - localstack
  #   environment:
  #     DYNAMO_ENDPOINT: http://localstack:4566
  #     AWS_REGION: ap-notrheast-1

  # sam:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/sam.Dockerfile
  #   container_name: sam
  #   # command: bash -c 'sam local start-api --host 0.0.0.0 --docker-network docker-lan'
  #   ports:
  #     - '3030:3000'
  # #   depends_on:
  # #     - localstack
  #   environment:
  #     SAM_DOCKER_VOLUME_BASEDIR: ${PWD}/sam
  #   env_file:
  #     - ./Envfiles/sam.env
  #   volumes:
  #     - ./App/sam:/app:cached
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   tty: true

  # sls:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/sls.Dockerfile
  #   container_name: sls
  #   # command: bash -c 'sls'
  #   ports:
  #     - '3030:3000'
  # #   depends_on:
  # #     - localstack
  #   env_file:
  #     - ./Envfiles/sls.env
  #   volumes:
  #     - ./App/sls:/app:cached
  #   tty: true

  # https-portal:
  #   image: steveltn/https-portal:1
  #   container_name: https-portal
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     # - rails
  #     - node
  #   depends_on:
  #     # - rails
  #     - node
  #   environment:
  #     WEBSOCKET: 'true'
  #     DOMAINS: 'loopback.forgxisto.com -> http://node:8000/'
  #     STAGE: local
  #   volumes:
  #     - ./LocalData/https-portal:/var/lib/https-portal
